### ISSUE TITLE
Crash after logging in and starting app

### ISSUE THREAD

**Issue by TheTimeWalker** [woachk/mastodon#2]
Device: Lumia 950 XL
Build: 15063.138
Instance: social.tchncs.de

As soon as you log in with correct details, the app crashes. Starting the app again makes it crash on splash screen after 1-2 seconds. Login seems to work as the app does appear in "authorized apps" on the Mastodon instance.

**Comment by woachk** [comment]
@TheTimeWalker Issue fixed in v1.0.10.0
