### ISSUE TITLE
Command bar turns light on tapping settings icon

### ISSUE THREAD

**Issue by tomfhowe** [woachk/mastodon#4]
![wp_ss_20170413_0005](https://cloud.githubusercontent.com/assets/19882099/25014797/4112e51c-2047-11e7-8a0d-73256f94bd0b.png)
I'm on version 1.0.16.0 on Lumia 950

**Comment by woachk** [comment]
Issue fixed in https://github.com/woachk/mastodon/commit/f2db5bbbf320dcd4c76ca86c46e99fe51f1345cc

**Comment by woachk** [comment]
Fixed in 1.0.17.0. Closing the issue.
